"""Rebuild _engine/questions.js from the question folders.

Run from anywhere:  python3 _engine/build.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
FILES = (("html", "index.html"), ("css", "style.css"), ("js", "script.js"))


def parse_question(md):
    lines = md.splitlines()
    heading = next(line for line in lines if line.startswith("# "))
    qid, title = (part.strip() for part in heading[2:].split("—", 1))
    sections, current = {}, None
    for line in lines:
        if line.startswith("## "):
            current = line[3:].strip()
            sections[current] = []
        elif current:
            sections[current].append(line)

    def bullets(name):
        return [line[2:].strip() for line in sections.get(name, []) if line.startswith("- ")]

    attempt = " ".join(line.strip() for line in sections.get("How to Attempt?", []) if line.strip())
    return {"id": qid, "title": title, "attempt": attempt,
            "objectives": bullets("Objectives"), "constraints": bullets("Constraints")}


def read_code(folder):
    return {key: (folder / name).read_text(encoding="utf-8") for key, name in FILES}


out = ["// GENERATED by _engine/build.py — edit the question folders, then re-run the build.",
       "window.QUESTIONS = [];"]
folders = sorted(p for p in ROOT.iterdir() if p.is_dir() and re.match(r"[A-Z]\d\d-", p.name))
for folder in folders:
    q = parse_question((folder / "QUESTION.md").read_text(encoding="utf-8"))
    q["folder"] = folder.name
    q["section"] = "pyq" if folder.name.startswith("Y") else "practice"
    q["starter"] = read_code(folder)
    q["solution"] = read_code(folder / "solution")
    q["explanation"] = (folder / "solution" / "EXPLANATION.md").read_text(encoding="utf-8")
    tests = (folder / "solution" / "tests.js").read_text(encoding="utf-8")
    out.append("QUESTIONS.push(Object.assign(" + json.dumps(q, ensure_ascii=False, indent=1) +
               ", { tests: (function () {\n" + tests + "\nreturn TESTS;\n})() }));")

(ROOT / "_engine" / "questions.js").write_text("\n".join(out) + "\n", encoding="utf-8")
print("Built", len(folders), "questions ->", ROOT / "_engine" / "questions.js")
